language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3
sudo: required
dist: trusty
group: deprecated-2017Q4

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  slack: thirtybees:L2Dyesn7En8jZ008IUwCrMnl

before_install:
  - composer install --prefer-dist --no-interaction --no-progress

install:
  - php install-dev/index_cli.php --newsletter=0 --language=en --country=us --domain=thirty.bees:8888 --db_name=thirtybees --db_create=1 --name=thirtybees --email=test@thirty.bees --firstname=thirty --lastname=bees --password=thirtybees

script:
  - tests/validate.sh
  - vendor/bin/codecept run unit,integration -c . --coverage --coverage-xml
  - phpenv config-rm xdebug.ini
  - php -S thirty.bees:8888 -t . >/dev/null 2>&1 &
  - phantomjs --webdriver=4444 >/dev/null 2>&1 &
  - sleep 10
  - vendor/bin/codecept run functional,acceptance -c .
  - if [ -f log/2* ]; then cat log/2*; false; fi

after_success:
  - php vendor/bin/coveralls -c .coveralls.yml

addons:
  hosts:
    - thirty.bees
