language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

notifications:
  slack: thirtybees:L2Dyesn7En8jZ008IUwCrMnl

before_install:
  - composer install --prefer-dist --no-interaction --no-progress

install:
  - php install-dev/index_cli.php --language=en --country=us --domain=127.0.0.1:8888 --db_name=tb.unit.test --db_create=1 --name=tb.unit.test --password=123456789

script:
  - vendor/bin/codecept run unit,integration -c . --coverage --coverage-xml
  - phpenv config-rm xdebug.ini
  - php -S 127.0.0.1:8888 -t . >/dev/null 2>&1 &
  - phantomjs --webdriver=4444 >/dev/null 2>&1 &
  - sleep 10
  - vendor/bin/codecept run functional,acceptance -c .

after_success:
  - php vendor/bin/coveralls -c .coveralls.yml
