---
- name: Add apt key for PHP ppa
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
    state: present

- name: Add apt repository for PHP
  apt_repository: repo='ppa:ondrej/php/ubuntu'

- name: Install python-software-properties
  apt: name=python-software-properties state=present

- name: Install PHP
  apt: name=php{{ php_version }} state=present

- name: Install required php packages
  apt: name={{ item }} state=present
  with_items:
    - php{{ php_version }}-bcmath
    - php{{ php_version }}-cli
    - php{{ php_version }}-common
    - php{{ php_version }}-curl
    - php{{ php_version }}-dom
    - php{{ php_version }}-gd
    - php{{ php_version }}-imap
    - php-imagick
    - php{{ php_version }}-imap
    - php{{ php_version }}-intl
    - php{{ php_version }}-json
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-mcrypt
    - php{{ php_version }}-mysql
    - php{{ php_version }}-opcache
    - php{{ php_version }}-readline
    - php-redis
    - php{{ php_version }}-soap
    - php{{ php_version }}-xml
    - php{{ php_version }}-zip

- name: Enable the MCrypt extension
  shell: phpenmod mcrypt

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

- name: Configure composer cache directory to avoid using slow NFS
  shell: composer config --global cache-dir /dev/shm/composer/cache
